language: python

addons:
  apt:
    sources:
      - sourceline: deb http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
      - sourceline: deb-src http://software.ligo.org/lscsoft/debian wheezy contrib
        key_url: http://software.ligo.org/keys/deb/lscsoft.key
    packages:
      - swig  # lal, m2crypto
      - libfftw3-dev  # lal
      - pkg-config  # lal
      - zlib1g-dev  # lal
      - libgsl0-dev  # lal
      - bc  # lal

env:
  global:
    - LAL_VERSION="6.18.0"

python:
  - '2.7'
  - '3.5'
  - 'nightly'

matrix:
  allow_failures:
    - python: '3.5'
    - python: 'nightly'
  fast_finish: true

before_install:
  # upgrade pip
  - pip install --quiet --upgrade pip
  # install requirements
  - pip install -r requirements.txt
  # install LAL from tarball
  - .travis/build-lal.sh
  # install test-only requirements
  - pip install coveralls

install:
  # install this package (need editable for coverage)
  - pip install --editable .

script:
  # test --help for all executables
  - . .travis/test-all-bin.sh

after_success:
  # submit coverage to coveralls.io
  - coverage report
  - coveralls

cache:
  apt: true
  pip: true
  directories:
    - lal-${LAL_VERSION}-${TRAVIS_PYTHON_VERSION}
