language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  # upgrade pip
  - pip install --quiet --upgrade pip
  # install requirements
  - pip install -r requirements.txt
  # install LAL (for glue)
  - pip install lalsuite
  # install test-only requirements
  - pip install coveralls

install:
  # install this package (need editable for coverage)
  - pip install --editable .

script:
  # test --help for all executables
  - . .travis/test-all-bin.sh

after_success:
  # submit coverage to coveralls.io
  - coverage report
  - coveralls

cache:
  pip: true
